name: 'ga4_project'
version: '1.0.0'
profile: 'ga4_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ga4_project:

    staging:
      +materialized: view

    core:
      +materialized: table

    marts:
      +materialized: table